[env:feather_s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = adafruit_feather_esp32s3_nopsram
framework = arduino
monitor_speed = 115200
board_build.partitions = default_8MB.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_filters = time, log2file
lib_deps =
    sensirion/Sensirion I2C SCD4x @ ^1.1.0
    adafruit/Adafruit SHT4x Library @ ^1.0.5
    adafruit/Adafruit VEML7700 Library @ ^2.1.6
    adafruit/Adafruit DPS310 @ ^1.1.4
    sensirion/Sensirion I2C SGP41
    sensirion/Sensirion Gas Index Algorithm
    sensirion/sensirion-sps
    tzapu/WiFiManager
    adafruit/Adafruit NeoPixel